### ISSUE TITLE
`daijin mikado` command fails

### ISSUE THREAD

**Issue by simonvh** [lucventurini/mikado#113] opened 2018-02-04 15:16 UTC
I have run `daijin assemble` without problems. Now, I want to run the `daijin mikado` command, but this fails with an error from snakemake. I have had a quick look at the code, but I don't see any differences between how `daijin assemble` and `daijin mikado` handle the config file. Any clues?

This is the config file created by daijin (renamed to .txt for github):
[mikado.yaml.txt](https://github.com/lucventurini/mikado/files/1692937/mikado.yaml.txt)

Let me know if you need any additional info.

```
$ daijin mikado xlaevis/mikado.yaml
2018-02-04 16:08:23,431 - main - __init__.py:510 - ERROR - main - MainProcess - Daijin crashed, cause:
2018-02-04 16:08:23,431 - main - __init__.py:511 - ERROR - main - MainProcess - config may only be a flat dict
Traceback (most recent call last):
  File "/home/simon/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/daijin/__init__.py", line 501, in main
    args.func(args)
  File "/home/simon/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/daijin/__init__.py", line 442, in mikado_pipeline
    lock=(not args.nolock))
  File "/home/simon/anaconda2/envs/mikado/lib/python3.5/site-packages/snakemake/__init__.py", line 333, in snakemake
    config_args = unparse_config(config)
  File "/home/simon/anaconda2/envs/mikado/lib/python3.5/site-packages/snakemake/__init__.py", line 603, in unparse_config
    raise ValueError("config may only be a flat dict")
ValueError: config may only be a flat dict
```

**Comment by lucventurini** [comment] 2018-02-05 10:39
Unfortunately I am unable to reproduce the bug on my machine. It might be related, however, to the bug fix I implemented in the lastest commit (c13e0ed). Would you be able to correct your installation to see whether it fixes your problem?

Please let me know about further developments on this issue, or further issues you might encounter.

**Comment by simonvh** [comment] 2018-02-05 21:55
That did it, thanks!
One additional small remark: diamond should probably be added to the dependencies.

**Comment by lucventurini** [comment] 2018-02-06 10:29
Thanks for the suggestion! I have just updated the README to state clearly the dependencies for the Daijin pipeline. I will close the issue for now, but please do not hesitate to contact me if you have further queries.

**Closed by lucventurini** 2018-02-06 10:29 UTC
Labels: bug
